# Generated by Django 5.1.3 on 2024-11-19 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.spycat'),
        ),
        migrations.AlterField(
            model_name='target',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.mission'),
        ),
    ]
