# Generated by Django 5.1.3 on 2024-11-19 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_mission_cat_alter_target_mission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='targets', to='api.mission'),
        ),
    ]
